"""Added the relationships and foreighn keys

Revision ID: 23cd908a4738
Revises: 57119af62a63
Create Date: 2025-12-01 11:39:08.525233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cd908a4738'
down_revision: Union[str, Sequence[str], None] = '57119af62a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'orders', 'tickets', ['ticket_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['buyer_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'events', ['event_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    # ### end Alembic commands ###
