"""Fix relationships

Revision ID: 7107b13ff4bf
Revises: 23cd908a4738
Create Date: 2025-12-01 11:44:07.516801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7107b13ff4bf'
down_revision: Union[str, Sequence[str], None] = '23cd908a4738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'escrows', ['order_id'])
    op.create_foreign_key(None, 'escrows', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'escrows', type_='foreignkey')
    op.drop_constraint(None, 'escrows', type_='unique')
    # ### end Alembic commands ###
